// Code generated by "stringer -type=orderState"; DO NOT EDIT.

package stringergeneratednames

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Created-0]
	_ = x[Paid-1]
	_ = x[Shipped-2]
	_ = x[Delivered-3]
	_ = x[Completed-4]
	_ = x[Cancelled-5]
}

const _orderState_name = "CreatedPaidShippedDeliveredCompletedCancelled"

var _orderState_index = [...]uint8{0, 7, 11, 18, 27, 36, 45}

func (i orderState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_orderState_index)-1 {
		return "orderState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _orderState_name[_orderState_index[idx]:_orderState_index[idx+1]]
}
