// Code generated by "stringer -type=orderTrigger"; DO NOT EDIT.

package stringergeneratednames

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pay-0]
	_ = x[Ship-1]
	_ = x[Deliver-2]
	_ = x[Complete-3]
	_ = x[Cancel-4]
}

const _orderTrigger_name = "PayShipDeliverCompleteCancel"

var _orderTrigger_index = [...]uint8{0, 3, 7, 14, 22, 28}

func (i orderTrigger) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_orderTrigger_index)-1 {
		return "orderTrigger(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _orderTrigger_name[_orderTrigger_index[idx]:_orderTrigger_index[idx+1]]
}
